# Generated by Django 4.0.3 on 2022-03-31 05:45

from django.db import migrations, models
import django.db.models.deletion
import utils.model_date


class Migration(migrations.Migration):

    dependencies = [
        ("ums", "0007_user_email_verified_userminoremailassociation_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pendingmodifypasswordemail",
            old_name="verified",
            new_name="hash1_verified",
        ),
        migrations.AddField(
            model_name="pendingmodifypasswordemail",
            name="hash2_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="PendingVerifyEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.TextField()),
                ("hash", models.CharField(max_length=100, unique=True)),
                (
                    "createdAt",
                    models.FloatField(default=utils.model_date.get_timestamp),
                ),
                ("verified", models.BooleanField(default=False)),
                ("is_major", models.BooleanField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ums.user"
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="pendingverifyemail",
            index=models.Index(fields=["hash"], name="ums_pending_hash_b80553_idx"),
        ),
    ]
