# Generated by Django 4.0.3 on 2022-04-11 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("rdts", "0009_remove_repository_url"),
        ("ums", "0011_remove_pendingverifyemail_verified"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserRemoteUsernameAssociation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("remote_name", models.CharField(max_length=255)),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rdts.repository",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ums.user"
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="userremoteusernameassociation",
            index=models.Index(
                fields=["remote_name", "repository"],
                name="ums_userrem_remote__db2e35_idx",
            ),
        ),
    ]
