# Generated by Django 4.0.3 on 2022-04-14 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ums", "0012_userremoteusernameassociation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pendingmodifypasswordemail",
            name="hash2",
            field=models.CharField(default="", max_length=100),
        ),
    ]
