# Generated by Django 4.0.3 on 2022-04-14 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ums", "0013_alter_pendingmodifypasswordemail_hash2"),
    ]

    operations = [
        migrations.CreateModel(
            name="Config",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=255)),
                ("value", models.TextField()),
            ],
        ),
        migrations.AddIndex(
            model_name="config",
            index=models.Index(fields=["key"], name="ums_config_key_84db69_idx"),
        ),
        migrations.RemoveIndex(
            model_name="userremoteusernameassociation",
            name="ums_userrem_remote__db2e35_idx",
        ),
        migrations.RemoveField(
            model_name="userremoteusernameassociation",
            name="repository",
        ),
        migrations.AddField(
            model_name="userremoteusernameassociation",
            name="url",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="userremoteusernameassociation",
            index=models.Index(
                fields=["remote_name", "url"], name="ums_userrem_remote__945b02_idx"
            ),
        ),
    ]
