# Generated by Django 4.0.3 on 2022-04-14 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ums", "0014_config_config_ums_config_key_84db69_idx"),
        (
            "ums",
            "0014_remove_userremoteusernameassociation_ums_userrem_remote__db2e35_idx_and_more",
        ),
    ]

    operations = []
