# Generated by Django 4.0.3 on 2022-04-16 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ums", "0014_config_config_ums_config_key_84db69_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="local_sr_title_pattern_extract",
            field=models.TextField(default="[\\s\\S]*"),
        ),
        migrations.AddField(
            model_name="project",
            name="remote_issue_iid_extract",
            field=models.TextField(default="(?<=\\(#)\\d+(?=\\))"),
        ),
        migrations.AddField(
            model_name="project",
            name="remote_sr_pattern_extract",
            field=models.TextField(default="(?<=\\[)SR.\\d{3}.\\d{3}(?=(.[I/F/B])?])"),
        ),
    ]
