# Generated by Django 4.0.3 on 2022-04-20 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ums", "0015_project_local_sr_title_pattern_extract_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
