# Generated by Django 4.0.3 on 2022-04-26 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ums", "0016_alter_user_email_alter_user_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="local_sr_title_pattern_extract",
        ),
    ]
