image: registry.secoder.net/tool/deployer

stages:
  - build
  - test
  - deploy

build-master:
  stage: build
  script:
    - cp ./config.yml.bak ./config.yml
    - export BUILD_IMAGE_NAME=$CI_REGISTRY_IMAGE
    - export BUILD_IMAGE_TAG=$CI_COMMIT_REF_SLUG
    - export BUILD_IMAGE_USERNAME=$CI_REGISTRY_USER
    - export BUILD_IMAGE_PASSWORD=$CI_REGISTRY_PASSWORD
    - deployer build
  only:
    - master

build-dev:
  stage: build
  script:
    - cp ./config.yml.bak ./config.yml
    - export BUILD_IMAGE_NAME=$CI_REGISTRY_IMAGE
    - export BUILD_IMAGE_TAG=$CI_COMMIT_REF_SLUG
    - export BUILD_IMAGE_USERNAME=$CI_REGISTRY_USER
    - export BUILD_IMAGE_PASSWORD=$CI_REGISTRY_PASSWORD
    - deployer build
  except:
    - master

style-test:
  image: python:3.8.5
  stage: test
  before_script:
    - cp ./config.yml.bak ./config.yml
    - pip install -i https://pypi.tuna.tsinghua.edu.cn/simple -r requirements.txt
  script:
    - pylint --load-plugins pylint_django --fail-under=0 --django-settings-module=backend.settings backend rms ums rdts
    - exit $?

#unit-test:
#  image: python:3.8.5
#  stage: test
#  before_script:
#    - cp ./config.yml.bak ./config.yml
#    - pip install -i https://pypi.tuna.tsinghua.edu.cn/simple -r requirements.txt
#  script:
#    - python manage.py makemigrations
#    - python manage.py migrate
#    - python manage.py createcachetable
#    - coverage run --source backend,ums,rms,rdts,utils -m pytest --junit-xml=xunit-reports/xunit-result.xml
#    - ret=$?
#    - coverage xml -o coverage-reports/coverage.xml
#    - coverage report
#    - exit $ret
#  after_script:
#    - SUFFIX=$RANDOM
#    - curl "http://10.0.0.11/sonar-scanner.tar.gz" -s -o "/tmp/sonar-$SUFFIX.tar.gz"
#    - tar -xf "/tmp/sonar-$SUFFIX.tar.gz"  -C /opt
#    - /opt/sonar-scanner/bin/sonar-scanner

deploy:
  stage: deploy
  script:
    - deployer dyno replace $CI_PROJECT_NAME "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" "$REGISTRY_USER" "$REGISTRY_PWD"
  only:
    - master

deploy-dev:
  stage: deploy
  script:
    - deployer dyno replace backend-dev "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" "$REGISTRY_USER" "$REGISTRY_PWD"
  only:
    - dev

deploy-feature-007-613:
  stage: deploy
  script:
    - deployer dyno replace backend-dev "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" "$REGISTRY_USER" "$REGISTRY_PWD"
  only:
    - feature-007-613
