# Generated by Django 4.0.3 on 2022-03-24 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdts', '0002_alter_repository_createdat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='createdAt',
            field=models.FloatField(default=1648138466.577152),
        ),
    ]
