# Generated by Django 4.0.3 on 2022-03-24 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rdts", "0003_alter_repository_createdat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="repository",
            name="createdAt",
            field=models.FloatField(default=1648138502.235897),
        ),
    ]
