# Generated by Django 4.0.3 on 2022-03-29 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rdts", "0003_alter_issue_assigneeusername_and_more"),
        ("rdts", "0004_alter_repository_createdat"),
    ]

    operations = []
