# Generated by Django 4.0.3 on 2022-03-29 02:25

from django.db import migrations, models
import utils.model_date


class Migration(migrations.Migration):

    dependencies = [
        ("rdts", "0005_merge_20220329_1013"),
    ]

    operations = [
        migrations.AlterField(
            model_name="repository",
            name="createdAt",
            field=models.FloatField(default=utils.model_date.get_timestamp),
        ),
    ]
