# Generated by Django 4.0.3 on 2022-03-30 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rms", "0006_projectiterationassociation_iriterationassociation"),
        ("rdts", "0006_alter_repository_createdat"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="repository",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="commitsrassociation",
            unique_together={("commit", "SR")},
        ),
        migrations.AlterUniqueTogether(
            name="issuesrassociation",
            unique_together={("issue", "SR")},
        ),
        migrations.AlterUniqueTogether(
            name="mrsrassociation",
            unique_together={("MR", "SR")},
        ),
    ]
