# Generated by Django 4.0.3 on 2022-04-08 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rdts', '0007_alter_repository_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueMRAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rdts.mergerequest')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rdts.issue')),
            ],
            options={
                'unique_together': {('issue', 'MR')},
            },
        ),
    ]
