# Generated by Django 4.0.3 on 2022-04-11 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rdts", "0008_issuemrassociation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="repository",
            name="url",
        ),
    ]
