# Generated by Django 4.0.3 on 2022-04-11 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ums", "0012_userremoteusernameassociation_and_more"),
        ("rdts", "0009_remove_repository_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="commit",
            name="user_committer",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="ums.user",
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="user_assignee",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="ums.user",
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="user_authored",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="ums.user",
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="user_closed",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="ums.user",
            ),
        ),
        migrations.AddField(
            model_name="mergerequest",
            name="user_authored",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="ums.user",
            ),
        ),
        migrations.AddField(
            model_name="mergerequest",
            name="user_reviewed",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="ums.user",
            ),
        ),
    ]
