# Generated by Django 4.0.3 on 2022-04-15 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rdts", "0013_repository_url_repository_rdts_reposi_url_13b1c1_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="remoterepo",
            name="secret_token",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="remoterepo",
            name="access_token",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="remoterepo",
            name="remote_id",
            field=models.TextField(default=""),
        ),
        migrations.AddIndex(
            model_name="remoterepo",
            index=models.Index(
                fields=["secret_token"], name="rdts_remote_secret__81ab73_idx"
            ),
        ),
    ]
