# Generated by Django 4.0.3 on 2022-04-15 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("rdts", "0014_remoterepo_secret_token_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PendingWebhookRequests",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.TextField()),
                (
                    "remote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rdts.remoterepo",
                    ),
                ),
            ],
        ),
    ]
