# Generated by Django 4.0.3 on 2022-04-16 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rdts", "0015_pendingwebhookrequests"),
    ]

    operations = [
        migrations.AddField(
            model_name="crawllog",
            name="is_webhook",
            field=models.BooleanField(default=False),
        ),
    ]
