# Generated by Django 4.0.3 on 2022-04-26 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rdts", "0016_crawllog_is_webhook"),
    ]

    operations = [
        migrations.AlterField(
            model_name="remoterepo",
            name="secret_token",
            field=models.CharField(default="", max_length=255, unique=True),
        ),
    ]
