# Generated by Django 4.0.3 on 2022-04-27 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rdts", "0017_alter_remoterepo_secret_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commit",
            name="title",
            field=models.TextField(),
        ),
    ]
