# Generated by Django 4.0.3 on 2022-05-09 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rdts", "0018_alter_commit_title"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="commit",
            name="rdts_commit_commite_d20353_idx",
        ),
        migrations.RemoveField(
            model_name="commit",
            name="diff",
        ),
        migrations.AddField(
            model_name="commit",
            name="commite_date",
            field=models.FloatField(default=0),
        ),
    ]
