# Generated by Django 4.0.3 on 2022-03-26 04:27

from django.db import migrations, models
import utils.model_date


class Migration(migrations.Migration):

    dependencies = [
        ('rms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ir',
            name='createdAt',
            field=models.FloatField(default=utils.model_date.get_timestamp),
        ),
        migrations.AlterField(
            model_name='iteration',
            name='createAt',
            field=models.FloatField(default=utils.model_date.get_timestamp),
        ),
        migrations.AlterField(
            model_name='service',
            name='createdAt',
            field=models.FloatField(default=utils.model_date.get_timestamp),
        ),
        migrations.AlterField(
            model_name='sr',
            name='createdAt',
            field=models.FloatField(default=utils.model_date.get_timestamp),
        ),
        migrations.AlterField(
            model_name='sr_changelog',
            name='changedAt',
            field=models.FloatField(default=utils.model_date.get_timestamp),
        ),
    ]
