# Generated by Django 4.0.3 on 2022-03-24 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rms", "0002_alter_ir_createdat_alter_iteration_createat_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ir",
            name="createdAt",
            field=models.FloatField(default=1648138466.577152),
        ),
        migrations.AlterField(
            model_name="iteration",
            name="createAt",
            field=models.FloatField(default=1648138466.577152),
        ),
        migrations.AlterField(
            model_name="service",
            name="createdAt",
            field=models.FloatField(default=1648138466.577152),
        ),
        migrations.AlterField(
            model_name="sr",
            name="createdAt",
            field=models.FloatField(default=1648138466.577152),
        ),
        migrations.AlterField(
            model_name="sr_changelog",
            name="changedAt",
            field=models.FloatField(default=1648138466.577152),
        ),
    ]
