# Generated by Django 4.0.3 on 2022-03-29 02:25

from django.db import migrations, models
import django.db.models.deletion
import utils.model_date


class Migration(migrations.Migration):

    dependencies = [
        ("rms", "0004_alter_ir_createdat_alter_iteration_createat_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ir",
            name="createdAt",
            field=models.FloatField(default=utils.model_date.get_timestamp),
        ),
        migrations.AlterField(
            model_name="iteration",
            name="createAt",
            field=models.FloatField(default=utils.model_date.get_timestamp),
        ),
        migrations.AlterField(
            model_name="service",
            name="createdAt",
            field=models.FloatField(default=utils.model_date.get_timestamp),
        ),
        migrations.AlterField(
            model_name="sr",
            name="createdAt",
            field=models.FloatField(default=utils.model_date.get_timestamp),
        ),
        migrations.AlterField(
            model_name="sr_changelog",
            name="changedAt",
            field=models.FloatField(default=utils.model_date.get_timestamp),
        ),
        migrations.CreateModel(
            name="ServiceSRAssociation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "SR",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rms.sr",
                        unique=True,
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="rms.service"
                    ),
                ),
            ],
        ),
    ]
