# Generated by Django 4.0.3 on 2022-03-30 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ums", "0006_alter_project_createdat_alter_sessionpool_expireat_and_more"),
        ("rms", "0005_alter_ir_createdat_alter_iteration_createat_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectIterationAssociation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "iteration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="rms.iteration"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ums.project"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IRIterationAssociation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "IR",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="rms.ir"
                    ),
                ),
                (
                    "iteration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="rms.iteration"
                    ),
                ),
            ],
            options={
                "unique_together": {("IR", "iteration")},
            },
        ),
    ]
