# Generated by Django 4.0.3 on 2022-03-31 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rms', '0007_alter_ir_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sr_changelog',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
