# Generated by Django 4.0.3 on 2022-04-05 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ums', '0011_remove_pendingverifyemail_verified'),
        ('rms', '0008_alter_sr_changelog_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSRAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rms.sr', unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ums.project')),
            ],
        ),
    ]
