# Generated by Django 4.0.3 on 2022-04-11 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rms", "0011_alter_sr_changelog_formerstate"),
    ]

    operations = [
        migrations.AddField(
            model_name="sr",
            name="pattern",
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name="sr",
            index=models.Index(fields=["pattern"], name="rms_sr_pattern_708bb8_idx"),
        ),
    ]
