# Generated by Django 4.0.3 on 2022-04-14 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rdts', '0013_repository_url_repository_rdts_reposi_url_13b1c1_idx'),
        ('rms', '0013_sr_changelog_autoaddcrawl_sr_changelog_autoadded_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sr_changelog',
            name='autoAddCrawl',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='rdts.crawllog'),
        ),
    ]
