# Generated by Django 4.0.3 on 2022-04-21 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rms", "0013_sr_changelog_autoaddcrawl_sr_changelog_autoadded_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sr_changelog",
            name="formerDescription",
            field=models.TextField(default=""),
        ),
    ]
