# Generated by Django 4.0.3 on 2022-04-26 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rms", "0014_alter_sr_changelog_formerdescription"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="sr",
            name="rms_sr_pattern_708bb8_idx",
        ),
        migrations.RemoveField(
            model_name="sr",
            name="pattern",
        ),
    ]
